services:
  - type: web
    name: safemailz-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: OAUTH_MOCK_MODE
        value: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: MS_CLIENT_ID
        sync: false
      - key: MS_CLIENT_SECRET
        sync: false
      - key: MS_REDIRECT_URI
        sync: false
